// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/oceanstack/rpc/req.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_req_840f986bab34f224, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type Response struct {
	Resp                 string   `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_req_840f986bab34f224, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "rpc.Request")
	proto.RegisterType((*Response)(nil), "rpc.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReQRePClient is the client API for ReQReP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReQRePClient interface {
	GetResp(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Cast(ctx context.Context, in *Request, opts ...grpc.CallOption) (*empty.Empty, error)
	StreamResponse(ctx context.Context, in *Request, opts ...grpc.CallOption) (ReQReP_StreamResponseClient, error)
	StreamRequest(ctx context.Context, opts ...grpc.CallOption) (ReQReP_StreamRequestClient, error)
	StreamReqRep(ctx context.Context, opts ...grpc.CallOption) (ReQReP_StreamReqRepClient, error)
}

type reQRePClient struct {
	cc *grpc.ClientConn
}

func NewReQRePClient(cc *grpc.ClientConn) ReQRePClient {
	return &reQRePClient{cc}
}

func (c *reQRePClient) GetResp(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.ReQReP/GetResp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reQRePClient) Cast(ctx context.Context, in *Request, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rpc.ReQReP/Cast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reQRePClient) StreamResponse(ctx context.Context, in *Request, opts ...grpc.CallOption) (ReQReP_StreamResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReQReP_serviceDesc.Streams[0], "/rpc.ReQReP/StreamResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &reQRePStreamResponseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReQReP_StreamResponseClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type reQRePStreamResponseClient struct {
	grpc.ClientStream
}

func (x *reQRePStreamResponseClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *reQRePClient) StreamRequest(ctx context.Context, opts ...grpc.CallOption) (ReQReP_StreamRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReQReP_serviceDesc.Streams[1], "/rpc.ReQReP/StreamRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &reQRePStreamRequestClient{stream}
	return x, nil
}

type ReQReP_StreamRequestClient interface {
	Send(*Request) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type reQRePStreamRequestClient struct {
	grpc.ClientStream
}

func (x *reQRePStreamRequestClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reQRePStreamRequestClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *reQRePClient) StreamReqRep(ctx context.Context, opts ...grpc.CallOption) (ReQReP_StreamReqRepClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReQReP_serviceDesc.Streams[2], "/rpc.ReQReP/StreamReqRep", opts...)
	if err != nil {
		return nil, err
	}
	x := &reQRePStreamReqRepClient{stream}
	return x, nil
}

type ReQReP_StreamReqRepClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type reQRePStreamReqRepClient struct {
	grpc.ClientStream
}

func (x *reQRePStreamReqRepClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reQRePStreamReqRepClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReQRePServer is the server API for ReQReP service.
type ReQRePServer interface {
	GetResp(context.Context, *Request) (*Response, error)
	Cast(context.Context, *Request) (*empty.Empty, error)
	StreamResponse(*Request, ReQReP_StreamResponseServer) error
	StreamRequest(ReQReP_StreamRequestServer) error
	StreamReqRep(ReQReP_StreamReqRepServer) error
}

func RegisterReQRePServer(s *grpc.Server, srv ReQRePServer) {
	s.RegisterService(&_ReQReP_serviceDesc, srv)
}

func _ReQReP_GetResp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReQRePServer).GetResp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ReQReP/GetResp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReQRePServer).GetResp(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReQReP_Cast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReQRePServer).Cast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ReQReP/Cast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReQRePServer).Cast(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReQReP_StreamResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReQRePServer).StreamResponse(m, &reQRePStreamResponseServer{stream})
}

type ReQReP_StreamResponseServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type reQRePStreamResponseServer struct {
	grpc.ServerStream
}

func (x *reQRePStreamResponseServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _ReQReP_StreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReQRePServer).StreamRequest(&reQRePStreamRequestServer{stream})
}

type ReQReP_StreamRequestServer interface {
	SendAndClose(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type reQRePStreamRequestServer struct {
	grpc.ServerStream
}

func (x *reQRePStreamRequestServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reQRePStreamRequestServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ReQReP_StreamReqRep_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReQRePServer).StreamReqRep(&reQRePStreamReqRepServer{stream})
}

type ReQReP_StreamReqRepServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type reQRePStreamReqRepServer struct {
	grpc.ServerStream
}

func (x *reQRePStreamReqRepServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reQRePStreamReqRepServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ReQReP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ReQReP",
	HandlerType: (*ReQRePServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResp",
			Handler:    _ReQReP_GetResp_Handler,
		},
		{
			MethodName: "Cast",
			Handler:    _ReQReP_Cast_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamResponse",
			Handler:       _ReQReP_StreamResponse_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRequest",
			Handler:       _ReQReP_StreamRequest_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamReqRep",
			Handler:       _ReQReP_StreamReqRep_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/oceanstack/rpc/req.proto",
}

func init() { proto.RegisterFile("src/oceanstack/rpc/req.proto", fileDescriptor_req_840f986bab34f224) }

var fileDescriptor_req_840f986bab34f224 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0xb5, 0x6a, 0xe1, 0xd4, 0x22, 0x74, 0x03, 0x42, 0x2d, 0x42, 0xa8, 0x03, 0xea,
	0x80, 0xec, 0x0a, 0x1e, 0x01, 0x21, 0x56, 0x30, 0x4f, 0xe0, 0x5a, 0x47, 0x06, 0x48, 0x7c, 0x39,
	0x3b, 0x03, 0x6f, 0xcd, 0x23, 0xa0, 0x24, 0x4e, 0x06, 0x86, 0x74, 0xfb, 0x6d, 0x7f, 0xff, 0xaf,
	0xcf, 0x70, 0x13, 0xc5, 0x9b, 0xe0, 0xc9, 0x55, 0x31, 0x39, 0xff, 0x65, 0x84, 0xbd, 0x11, 0xaa,
	0x35, 0x4b, 0x48, 0x01, 0x67, 0xc2, 0x7e, 0xb3, 0x2d, 0x42, 0x28, 0xbe, 0xc9, 0x74, 0x57, 0xc7,
	0xe6, 0xd3, 0x50, 0xc9, 0xe9, 0xa7, 0x27, 0x76, 0x5b, 0x58, 0x5a, 0xaa, 0x1b, 0x8a, 0x09, 0x2f,
	0x61, 0x26, 0x54, 0x5f, 0xab, 0x3b, 0xb5, 0x3f, 0xb7, 0x6d, 0xdc, 0xdd, 0xc2, 0x99, 0xa5, 0xc8,
	0xa1, 0x8a, 0x84, 0x08, 0x73, 0xa1, 0xc8, 0xf9, 0xb9, 0xcb, 0x8f, 0xbf, 0x0a, 0x16, 0x96, 0xde,
	0x2d, 0xbd, 0xe1, 0x3d, 0x2c, 0x5f, 0x29, 0xb5, 0x34, 0xae, 0xb4, 0xb0, 0xd7, 0x79, 0x75, 0xb3,
	0xce, 0xa7, 0x3c, 0xf3, 0x00, 0xf3, 0x67, 0x17, 0xd3, 0x3f, 0xe8, 0x4a, 0xf7, 0x8e, 0x7a, 0x70,
	0xd4, 0x2f, 0xad, 0x23, 0x1a, 0xb8, 0xf8, 0x48, 0x42, 0xae, 0x1c, 0xfb, 0x53, 0xe3, 0x07, 0x85,
	0x1a, 0xd6, 0x43, 0xa1, 0xff, 0xd4, 0x14, 0xbf, 0x57, 0x68, 0x60, 0x35, 0xf2, 0x96, 0xf8, 0x04,
	0x7e, 0x50, 0xc7, 0x45, 0x67, 0xf8, 0xf4, 0x17, 0x00, 0x00, 0xff, 0xff, 0x48, 0xff, 0x15, 0xd9,
	0x78, 0x01, 0x00, 0x00,
}
